config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "movies#index"

  # it is possible to provide a star rating

  post   '/ratings/create', to: "ratings#create"
  patch  '/ratings/update', to: "ratings#update"
  delete '/ratings/destroy', to: "ratings#destroy"

  resources :movies do
    collection do
      get :show
      get :show_rated_by_user
      get :sort_movies_by_popularity
      post :set_search_option
    end
  end

  namespace :admin do
    resources :movies, except: %i[index show]
  end

  get "/up/", to: "up#index", as: :up
  get "/up/databases", to: "up#databases", as: :up_databases

  # Sidekiq has a web dashboard which you can enable below. It's turned off by
  # default because you very likely wouldn't want this to be available to
  # everyone in production.
  #
  # Uncomment the 2 lines below to enable the dashboard WITHOUT authentication,
  # but be careful because even anonymous web visitors will be able to see it!
  # require "sidekiq/web"
  # mount Sidekiq::Web => "/sidekiq"
  #
  # If you add Devise to this project and happen to have an admin? attribute
  # on your user you can uncomment the 4 lines below to only allow access to
  # the dashboard if you're an admin. Feel free to adjust things as needed.
  # require "sidekiq/web"
  # authenticate :user, lambda { |u| u.admin? } do
  #   mount Sidekiq::Web => "/sidekiq"
  # end

  # Learn more about this file at: https://guides.rubyonrails.org/routing.html
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :ratings
  has_many :movie_categories
  has_many :categories, through: :movie_categories

  # img attached (active storage)
  has_one_attached :image

  # trix editor
  # Note: you don't need to add Movie.text (Movie.content) field to your messages table [https://edgeguides.rubyonrails.org/action_text_overview.html]
  # But in this situation I use existing field Movie.text, and everything works
  has_rich_text :text

  # Paginator [https://github.com/kaminari/kaminari]
  paginates_per 30 # default

  scope :already_rated, -> { where.not(rating: 0) }
  scope :not_rated_yet, -> { where(rating: 0) }

  # validations

  validates_presence_of :title, :rating

  validates :title, presence: true

  validates :rating, numericality: { in: 0..10 }

  # search for movies on the home (root) page by title
  scope :search_movies_by_title, ->(title) { Movie.where('LOWER(title) LIKE ?', "%#{title.downcase}%").order(id: :desc) }

  def self.search_movies_by_categories(string_of_categories)
    return Movie.all if string_of_categories.nil? || (string_of_categories == '')

    array_of_category_ids = Array.new

    Category.all.each do |i|
      array_of_category_ids.append(i.id) if string_of_categories.include? i.name
    end

    movie_ids = MovieCategory.where(category_id: array_of_category_ids).map(&:movie_id).uniq

    Movie.where(id: movie_ids).order(id: :desc)
  end
end

app/views/layouts/_flash.html.erb
<% if notice %>
      <div id="alert-1" class="flex p-4 mb-4 text-blue-700 bg-blue-100 rounded-lg dark:bg-gray-800 dark:text-blue-400" role="alert">
        <svg aria-hidden="true" class="flex-shrink-0 w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clip-rule="evenodd"></path></svg>
        <span class="sr-only">Notice</span>
        <div class="ml-3 text-sm font-medium">
          <%= notice %>
        </div>
        <button type="button" class="ml-auto -mx-1.5 -my-1.5 bg-blue-100 text-blue-500 rounded-lg focus:ring-2 focus:ring-blue-400 p-1.5 hover:bg-blue-200 inline-flex h-8 w-8 dark:bg-gray-800 dark:text-blue-400 dark:hover:bg-gray-700" data-dismiss-target="#alert-1" aria-label="Close">
          <span class="sr-only">Close</span>
          <svg aria-hidden="true" class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
        </button>
      </div>
    <% end %>
    <% if alert %>
      <div id="alert-2" class="flex p-4 mb-4 text-red-700 bg-red-100 rounded-lg dark:bg-gray-800 dark:text-red-400" role="alert">
        <svg aria-hidden="true" class="flex-shrink-0 w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clip-rule="evenodd"></path></svg>
        <span class="sr-only">Alert</span>
        <div class="ml-3 text-sm font-medium">
          <%= alert %>
        </div>
        <button type="button" class="ml-auto -mx-1.5 -my-1.5 bg-red-100 text-red-500 rounded-lg focus:ring-2 focus:ring-red-400 p-1.5 hover:bg-red-200 inline-flex h-8 w-8 dark:bg-gray-800 dark:text-red-400 dark:hover:bg-gray-700" data-dismiss-target="#alert-2" aria-label="Close">
          <span class="sr-only">Close</span>
          <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
        </button>
      </div>
<% end %>

app/views/layouts/_iconuser.html.erb
<div class="flex flex-wrap items-top justify-end place-items-top">
  <!--User icon-->
  <% if current_user %>
    <div class="flex items-center md:order-2">
      <button type="button" class="flex mr-3 text-sm bg-white-800 rounded-full md:mr-0 focus:ring-4 focus:ring-gray-300 dark:focus:ring-gray-600" id="user-menu-button" aria-expanded="false" data-dropdown-toggle="user-dropdown" data-dropdown-placement="bottom">
        <span class="sr-only">Open user menu</span>
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-10 h-10 bg-blue-100 rounded-full">
          <path fill-rule="evenodd" d="M18.685 19.097A9.723 9.723 0 0021.75 12c0-5.385-4.365-9.75-9.75-9.75S2.25 6.615 2.25 12a9.723 9.723 0 003.065 7.097A9.716 9.716 0 0012 21.75a9.716 9.716 0 006.685-2.653zm-12.54-1.285A7.486 7.486 0 0112 15a7.486 7.486 0 015.855 2.812A8.224 8.224 0 0112 20.25a8.224 8.224 0 01-5.855-2.438zM15.75 9a3.75 3.75 0 11-7.5 0 3.75 3.75 0 017.5 0z" clip-rule="evenodd" />
        </svg>
      </button>
      <!-- Dropdown menu -->
      <div class="z-50 hidden my-4 text-base list-none bg-white divide-y divide-gray-100 rounded shadow dark:bg-gray-700 dark:divide-gray-600" id="user-dropdown">
        <div class="px-4 py-3">
          <span class="block text-sm text-gray-900 dark:text-white"><%= current_user.role %></span>
          <span class="block text-sm font-medium text-gray-500 truncate dark:text-gray-400"><%= current_user.email %></span>
        </div>
        <ul class="py-1" aria-labelledby="user-menu-button">
          <% if current_user.role != 'user' %>
            <li>
              <a href="/admin/movies/new" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white">Add new movie</a>
            </li>
          <% end %>
          <li>
            <a href="/users/edit" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white">Settings</a>
          </li>
          <li>
            <a href="/movies/show_rated_by_user" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white">Rated movies</a>
          </li>
          <li>
            <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "block py-2 px-4 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white" %>
          </li>
        </ul>
      </div>
    </div>
  <% else %>
    <ul class="py-1" aria-labelledby="user-menu-button">
      <li>
        <a href="/users/sign_in" class="block py-2 px-4 text-sm text-gray-100 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white">Log in</a>
      </li>
      <li>
        <a href="/users/sign_up" class="block py-2 px-4 text-sm text-gray-100 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white">Sign up</a>
      </li>
    </ul>
  <% end %>
</div>

app/views/layouts/_search.html.erb
<%#= stylesheet_link_tag 'multi-selects/slimselect.css' %>
<%#= javascript_include_tag 'multi-selects/slimselect.min.js' %>

<!--
<script src="https://unpkg.com/slim-select@latest/dist/slimselect.min.js"></script>
<link href="https://unpkg.com/slim-select@latest/dist/slimselect.css" rel="stylesheet"></link>
-->

<%= stylesheet_link_tag 'multi-selects/multi-select-tag' %>
<%= javascript_include_tag 'multi-selects/multi-select-tag' %>

<!--
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/habibmhamadi/multi-select-tag/dist/css/multi-select-tag.css">
<script src="https://cdn.jsdelivr.net/gh/habibmhamadi/multi-select-tag/dist/js/multi-select-tag.js"></script>
-->

  <%= form_with(url: '/movies/set_search_option') do |form| %>
    <div class="flex flex-wrap items-top justify-left place-items-top">
      <div class=" max-w-xs my-2">
        <p class="text-gray-500 text-xs">Select Categories</p>
        <!--https://slimselectjs.com/install#cdn-->
        <%= form.select :category_ids, Category.pluck(:name, :id), {}, { multiple: true, id: 'selectCategoriesSearch', class: 'text-ms' } %>
      </div>
      &nbsp&nbsp&nbsp
      <div class="flex">
        <%= form.text_field :title, id: "search_movie_by_title", class: "w-full block py-2.5 z-20 text-sm text-gray-900 bg-gray-50 border-gray-300", placeholder: " Movie title..." %>
        <%= form.submit "Search", class: "pl-2 rounded-r-lg border-l-gray-50 py-2 px-3 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
        &nbsp&nbsp&nbsp&nbsp&nbsp
      </div>

      <div class="flex my-2">
        <%= link_to "By popularity", "/movies/sort_movies_by_popularity", class: 'text-white bg-gradient-to-br from-pink-500 to-orange-400 hover:bg-gradient-to-bl focus:ring-4 focus:outline-none focus:ring-pink-200 dark:focus:ring-pink-800 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2' %>
      </div>
    </div>
  <% end %>

<!--In this case I use this multiple select instead of SlimSelect due to the fact that SlimSelect requires more time to load-->
<script type="text/javascript">
    new MultiSelectTag('selectCategoriesSearch')
</script>

<!--Search hint by title jQuery-ui-->
<!--Not awesome but works-->
<script type="text/javascript">
    $(function() {
        $( "#search_movie_by_title" ).autocomplete({
            source: [ <% @array_names_of_movie.length.times do |t| %>"<%= @array_names_of_movie.at(t) %>", <% end %>],
        })
    })
</script>

<!--https://slimselectjs.com/install#cdn-->
<!--Delete this script if you don't want to see slim select on the header of the page (if you delete then there will be a standard html multi select)-->
<script type="text/javascript">
    /*
    var select = new SlimSelect({
        select: '#selectCategoriesSearch',
        settings: {
            allowDeselect: true,
            placeholderText: 'Select categories'
        }
    })
    */
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>GoodFilm</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Rails IMDb clone with Docker & Docker Compose">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

    <%# Generated with: https://realfavicongenerator.net/ %>
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/site.webmanifest">
    <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#61b9d2">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">

    <!--
      include Flowbite via CDN with turbo support
    -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.2/flowbite.turbo.min.js"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.3/flowbite.min.css" rel="stylesheet" />


    <!--for jquery-ui-->
    <link rel="stylesheet" href="//code.jquery.com/ui/1.13.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/jquery-3.6.0.js"></script>
    <script src="https://code.jquery.com/ui/1.13.1/jquery-ui.js"></script>

    <!--Background image gradient-->
    <style type="text/css">
        body {
            background-image: url('/assets/back_ground_img');
            background-size: cover;
            background-repeat: space;
        }
    </style>
  </head>

  <body class="flex flex-col h-screen justify-between">
    <!--This is header-->
    <header id="my_own_application_header">
      <nav class="bg-gray-800 border-gray-200 px-2 sm:px-4 py-2.5">
        <div class="container flex flex-wrap items-center justify-between mx-auto">
          <div class="flex">
            <a href="/" class="flex items-center">
              <img src="https://i.imgur.com/MNfUK91.png" class="h-6 mr-3 sm:h-9" alt="IMDb Logo" />
            </a>
            &nbsp&nbsp&nbsp
            <!--This is usericon-->
            <%= render partial: 'layouts/iconuser' %>
          </div>
            <!--Here filter by categories and search by title-->
            <%= render partial: 'layouts/search' %>
        </div>
      </nav>
    </header>

    <!--Devise messages will appear here-->
    <%= render partial: 'layouts/flash' %>

    <!--This is main content of a page-->
    <main class="mx-auto mb-auto container">
      <%= yield %>
    </main>

    <!--This is footer-->
    <footer class="bg-gray-700 text-center lg:text-left">
      <div class="text-gray-100 text-center p-4" style="background-color: rgba(0, 0, 0, 0.2);">
        © 2023 Author:
        <a class="text-gray-100" href="#">Yelysei Nazarenko</a>
      </div>
    </footer>
  </body>
</html>